import type { Language } from "../types/language";

export const LANGUAGES: Language[] = [
  {
    id: "pt",
    label: "Português",
    nativeLabel: "Português",
    openAIOutputLanguageCode: "pt",
    shortName: "PT",
    themeColor: "#f26e5f",
    gradient: "linear-gradient(135deg, #f9bf5a 0%, #f26e5f 48%, #d94c74 100%)",
    examplePhrase: "Fale naturalmente",
  },
  {
    id: "en",
    label: "English",
    nativeLabel: "English",
    openAIOutputLanguageCode: "en",
    shortName: "EN",
    themeColor: "#3c7bdc",
    gradient: "linear-gradient(135deg, #5ec9f5 0%, #3c7bdc 52%, #6347c6 100%)",
    examplePhrase: "Speak naturally",
  },
  {
    id: "es",
    label: "Español",
    nativeLabel: "Español",
    openAIOutputLanguageCode: "es",
    shortName: "ES",
    themeColor: "#f09d44",
    gradient: "linear-gradient(135deg, #ffd36e 0%, #f09d44 48%, #e35d57 100%)",
    examplePhrase: "Habla naturalmente",
  },
  {
    id: "fr",
    label: "Français",
    nativeLabel: "Français",
    openAIOutputLanguageCode: "fr",
    shortName: "FR",
    themeColor: "#8561d8",
    gradient: "linear-gradient(135deg, #9dd9ff 0%, #8561d8 50%, #d56ba7 100%)",
    examplePhrase: "Parlez naturellement",
  },
  {
    id: "de",
    label: "Deutsch",
    nativeLabel: "Deutsch",
    openAIOutputLanguageCode: "de",
    shortName: "DE",
    themeColor: "#56616f",
    gradient: "linear-gradient(135deg, #aab7c3 0%, #56616f 52%, #2f343b 100%)",
    examplePhrase: "Sprich natürlich",
  },
  {
    id: "it",
    label: "Italiano",
    nativeLabel: "Italiano",
    openAIOutputLanguageCode: "it",
    shortName: "IT",
    themeColor: "#45b990",
    gradient: "linear-gradient(135deg, #98e6bd 0%, #45b990 52%, #22806f 100%)",
    examplePhrase: "Parla naturalmente",
  },
  {
    id: "ja",
    label: "日本語",
    nativeLabel: "日本語",
    openAIOutputLanguageCode: "ja",
    shortName: "JA",
    themeColor: "#dd6f90",
    gradient: "linear-gradient(135deg, #ffd7df 0%, #dd6f90 52%, #9d4f9d 100%)",
    examplePhrase: "自然に話してください",
  },
  {
    id: "ko",
    label: "한국어",
    nativeLabel: "한국어",
    openAIOutputLanguageCode: "ko",
    shortName: "KO",
    themeColor: "#5c8fe8",
    gradient: "linear-gradient(135deg, #a6e6ff 0%, #5c8fe8 50%, #7d5bd6 100%)",
    examplePhrase: "자연스럽게 말하세요",
  },
  {
    id: "zh",
    label: "中文",
    nativeLabel: "中文",
    openAIOutputLanguageCode: "zh",
    shortName: "ZH",
    themeColor: "#d35555",
    gradient: "linear-gradient(135deg, #ffc55f 0%, #d35555 50%, #a63d63 100%)",
    examplePhrase: "自然地说话",
  },
  {
    id: "ar",
    label: "العربية",
    nativeLabel: "العربية",
    openAIOutputLanguageCode: "ar",
    shortName: "AR",
    themeColor: "#9f7a46",
    gradient: "linear-gradient(135deg, #dec477 0%, #9f7a46 52%, #5f5a3f 100%)",
    examplePhrase: "تحدث بشكل طبيعي",
  },
  {
    id: "hi",
    label: "हिन्दी",
    nativeLabel: "हिन्दी",
    openAIOutputLanguageCode: "hi",
    shortName: "HI",
    themeColor: "#d96d42",
    gradient: "linear-gradient(135deg, #ffd77d 0%, #d96d42 49%, #4aa874 100%)",
    examplePhrase: "स्वाभाविक रूप से बोलें",
  },
];

export function getLanguageById(id: string) {
  return LANGUAGES.find((language) => language.id === id) ?? LANGUAGES[0];
}
